version: "3.9"

# Common variables, shared between main and edge instances
x-fastapi-variables: &fastapi-variables
  FORWARDED_ALLOW_IPS: "*"

services:
  # Prerequisites
  redis:
    image: redis
    restart: always

  redis_edge:
    image: redis
    restart: always

  # API containers
  fastapi:
    image: "ghcr.io/renalreg/ukrdc-fastapi:latest"
    volumes:
      - ./data:/app/data
    environment:
      <<: *fastapi-variables
      REDIS_HOST: "redis"
    env_file: .env
    depends_on:
      - redis
    restart: always

  fastapi_edge:
    image: "ghcr.io/renalreg/ukrdc-fastapi:edge"
    volumes:
      - ./data:/app/data
    environment:
      <<: *fastapi-variables
      REDIS_HOST: "redis_edge"
    env_file: .env
    depends_on:
      - redis
    restart: always

  # Frontend containers
  nuxt:
    image: "ghcr.io/renalreg/ukrdc-nuxt-3:latest"
    env_file: .env
    restart: always

  nuxt_edge:
    image: "ghcr.io/renalreg/ukrdc-nuxt-3:edge"
    env_file: .env
    restart: always

  # "Binding" proxy
  nginx:
    image: "nginx:latest"
    volumes:
      - ./templates:/etc/nginx/templates
    ports:
      - 9999:9999
    env_file: .env
    depends_on:
      - fastapi
      - nuxt
      - nuxt_edge
    restart: always

# Prevent collision with ARO back-LAN IP ranges
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.100.0.0/24