version: "3.9"

services:
  fastapi:
    image: ghcr.io/renalreg/ukrdc-fastapi:main
    environment:
      # FORWARDED_ALLOW_IPS: Allowing all (*) is a temporary solution.
      # We cannot resolve the proxy IP at runtime, and since it's unknown
      # until the container is running, we need to just allow all for now.
      # Our public-facing reverse proxy should negate any security risks.
      - FORWARDED_ALLOW_IPS=*
      - REDIS_HOST=redis
    env_file: .env
    ports:
      - 8000:8000
    depends_on:
      - redis

  redis:
    image: redis

  nuxt:
    image: ghcr.io/renalreg/ukrdc-nuxt:main
    environment:
      # Base API URL for server-side (SSR) requests
      - BASE_URL=http://fastapi:8000
      # Base API URL for browser-side (SPA) requests
      - BROWSER_BASE_URL=/
    env_file: .env
    ports:
      - 3000:3000

  nginx:
    image: nginx:1.19.6
    volumes:
      - ./templates:/etc/nginx/templates
    ports:
      - 9999:9999
    environment:
      - API_HOST=fastapi
      - API_PORT=8000
      - APP_HOST=nuxt
      - APP_PORT=3000
      - PORT=9999
    env_file: .env
