version: "3.9"

services:
  fastapi:
    image: "ghcr.io/renalreg/ukrdc-fastapi:latest"
    environment:
      - FORWARDED_ALLOW_IPS=*
      - REDIS_HOST=redis
    env_file: .env
    depends_on:
      - redis
    restart: always

  redis:
    image: redis
    restart: always

  nuxt:
    image: "ghcr.io/renalreg/ukrdc-nuxt:latest"
    environment:
      - API_BASE_URL=/api
    env_file: .env
    restart: always

  nginx:
    image: nginx:1.19.6
    volumes:
      - ./templates:/etc/nginx/templates
    ports:
      - 9999:9999
    environment:
      - API_HOST=fastapi
      - API_PORT=8000
      - API_BASE=/api
      - APP_HOST=nuxt
      - APP_PORT=3000
      - APP_BASE=/app
      - PORT=9999
    env_file: .env
    depends_on:
      - fastapi
      - nuxt
    restart: always
