version: "3.9"

services:
  fastapi:
    image: "ghcr.io/renalreg/ukrdc-fastapi:latest"
    volumes:
      - ./data:/app/data
    environment:
      - FORWARDED_ALLOW_IPS=*
      - REDIS_HOST=redis
    env_file: .env
    depends_on:
      - redis
    restart: always

  redis:
    image: redis
    restart: always

  nuxt:
    image: "ghcr.io/renalreg/ukrdc-nuxt:latest"
    env_file: .env
    restart: always

  nuxt3:
    image: "ghcr.io/renalreg/ukrdc-nuxt-3:latest"
    env_file: .env
    restart: always

  nginx:
    image: nginx:1.19.6
    volumes:
      - ./templates:/etc/nginx/templates
    ports:
      - 9999:9999
    env_file: .env
    depends_on:
      - fastapi
      - nuxt
      - nuxt3
    restart: always
