version: "3.9"

services:
  fastapi:
    image: "ghcr.io/renalreg/ukrdc-fastapi:latest"
    environment:
      - FORWARDED_ALLOW_IPS=*
      - REDIS_HOST=redis
    env_file: .env
    ports:
      - 8000:8000
    depends_on:
      - redis
    restart: always

  redis:
    image: redis
    restart: always

  nuxt:
    image: "ghcr.io/renalreg/ukrdc-nuxt:latest"
    environment:
      # Base API URL for server-side (SSR) requests
      - BASE_URL=http://fastapi:8000
      # Base API URL for browser-side (SPA) requests
      - BROWSER_BASE_URL=/
    env_file: .env
    ports:
      - 3000:3000
    restart: always

  nginx:
    image: nginx:1.19.6
    volumes:
      - ./templates:/etc/nginx/templates
    ports:
      - 9999:9999
    environment:
      - API_HOST=fastapi
      - API_PORT=8000
      - API_BASE=/new/api
      - APP_HOST=nuxt
      - APP_PORT=3000
      - APP_BASE=/new/app
      - PORT=9999
    env_file: .env
    depends_on:
      - fastapi
      - nuxt
    restart: always
